// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMd1DE5k0L1LOPgrNPWimtkT45pr3XkE',
    appId: '1:40042091076:android:4df4ffa82de8adaa7ee211',
    messagingSenderId: '40042091076',
    projectId: 'perfect-elearnn',
    storageBucket: 'perfect-elearnn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHDxlQtw-XAT1djFwFFalx7GJiuxlmog',
    appId: '1:40042091076:ios:d5df252a65da75c17ee211',
    messagingSenderId: '40042091076',
    projectId: 'perfect-elearnn',
    storageBucket: 'perfect-elearnn.firebasestorage.app',
    androidClientId: '40042091076-nfe6nos8k5t53anc4qkdq485gr1t6ap2.apps.googleusercontent.com',
    iosClientId: '40042091076-01ov0tmb3rfun8q64vuder60bst8ppee.apps.googleusercontent.com',
    iosBundleId: 'com.example.perfect',
  );

}